function [outboundString, fileLocations] = pyTrussSolve_input(inputArray)
%pyTrussSolve_input Scheduals a job to solve a truss, and handles the
%output to the Discord Bot
%   Detailed explanation goes here

[...
    nodeLocations,...
    connectionsMatrix,...
    weightNode,...
    safteyFactor,...
    maxCost, ...
    discordID...
    ] = deal(inputArray{:});
[trussGraph, trussStruct] = pyTrussSolve_jobFunction(...
    nodeLocations,...
    connectionsMatrix,...
    weightNode,...
    safteyFactor,...
    maxCost...
    );
f = figure('Visible','off');
graphPlot = plot(trussGraph,'XData',trussGraph.Nodes.x,'YData',trussGraph.Nodes.y,...
   'Marker','s','MarkerSize',5);
ax = ancestor(graphPlot,'axes');
axis(ax,'ij');
axis(ax,'equal');
ax.YDir = 'normal';
fileLocations = append('C:\Users\Mack\Documents\MATLAB\Truss Solver\OutboundGraphics\',int2str(discordID),'.png');
exportgraphics(f,fileLocations);
close(f)
outboundString = sprintf('Truss Cost: $%.2f\nTruss Capasity: %.3fN', trussStruct.cost, trussStruct.capasity);
end

