%
% region definitions
%

% loading region definition
loading_region = zones( ...
    shapes.rectangle, ...
    zoneType.load, ...
    [0.150, 0.150; 0.200, -0.150] ...
);

% restricted region definitions
left_support_platform = zones( ...
    shapes.rectangle, ...
    zoneType.platform, ...
    [-0.150, -0.001; 0, -0.150] ...
);
right_support_platform = zones( ...
    shapes.rectangle, ...
    zoneType.platform, ...
    [0.450, -0.001; 0.600, -0.150] ...
);
bottom_forbidden_zone_1 = zones( ...
    shapes.rectangle, ...
    zoneType.restricted, ...
    [0.350, -0.001; 0.450, -0.150] ...
);
bottom_forbidden_zone_2 = zones( ...
    shapes.rectangle, ...
    zoneType.restricted, ...
    [0, -0.150; 0.450, -0.160] ...
);
circle_forbidden_zone = zones( ...
    shapes.circle, ...
    zoneType.restricted, ...
    [0.025, 0.025, 0.125] ...
);

restricted_zones = { ...
    left_support_platform, ...
    right_support_platform, ...
    bottom_forbidden_zone_1, ...
    bottom_forbidden_zone_2, ...
    circle_forbidden_zone ...
};

save region_definitions